---
title: "WM119 vs DMS0 (only 888)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("~/RNA_seq_KAT6Ainhibitor_small_dataset/Chemical Inhibitor WM1119 vs DMSO (only 888)")

#Libraries and load in Data

library(tidyverse)
library(readxl)
library(dplyr)
library(pkgbuild) ##load pkgbuild
library(DESeq2) ##Load in Deseq library

countdata <-read_excel("KAT6A-inhibitors-controlNPC-CountMatrix_AN008D_221228 (1).xlsx")
  
countdata <- as.data.frame(countdata)
row.names(countdata) <- countdata[,1]
countdata <- countdata[,-1]

coldata <- data.frame(read_excel("KAT6A-inhibitors-controlNPC-colData-sampleINFO_AN008D_221228.xlsx"))

rownames(coldata)<-coldata[,1]
coldata<-coldata[,-1]

countdata<-data.frame(countdata)
```


```{r}

# Filter coldata for WM1119, DMSO, and the 888 cell line
filtered_coldata <- coldata %>%
  filter((Drug == "WM1119" | str_starts(Drug, "DMSO")) & Line == "888")

# Extract sample names from the filtered coldata
sample_names <- filtered_coldata$sampleID


# Select only the countdata columns that match these filtered sample names
countdata <- countdata %>%
  dplyr::select(all_of(sample_names))

# View the results
view(countdata)
#view(filtered_coldata)

```


```{r}

```


