---
title: "WM1119 vs DMSO try #3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Compare WM8014 to DMSO

setwd("~/RNA_seq_KAT6Ainhibitor_small_dataset/Chemical Inhibitor WM1119 vs DMSO (only 888)")

#Libraries and load in Data

library(tidyverse)
library(readxl)
library(dplyr)
library(pkgbuild) ##load pkgbuild
library(DESeq2) ##Load in Deseq library

countdata <-read_excel("KAT6A-inhibitors-controlNPC-CountMatrix_AN008D_221228 (1).xlsx")
  
countdata <- as.data.frame(countdata)
row.names(countdata) <- countdata[,1]
countdata <- countdata[,-1]

coldata <- data.frame(read_excel("KAT6A-inhibitors-controlNPC-colData-sampleINFO_AN008D_221228.xlsx"))

rownames(coldata)<-coldata[,1]
coldata<-coldata[,-1]

countdata<-data.frame(countdata)
```




```{r}

dds<-DESeqDataSetFromMatrix(countData = countdata, colData = coldata, design = ~ timept + Line + Drug)

dds<-DESeq(dds)

dispersion_graph <-plotDispEsts(dds)
```
```{r}



```


```{r}
#make pca
rld<-rlog(dds,blind = TRUE)
#making fancy pca with labels 
#this is to plot the points on the PCA from DESeq2 with sample names on them
pcaData<-plotPCA(rld,intgroup=c("Drug", "timept", "Line","Dosage"),returnData=TRUE)
percentVar<-round(100*attr(pcaData,"percentVar"))
pcaData<-merge(x=pcaData,y=coldata,by=0)
library(ggplot2)
library(ggrepel)
ggplot(pcaData, aes(PC1, PC2, color=Drug.x, shape=Source ,label=name)) +
  geom_point(size=3) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))+
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()
```

```{r}

```

